version: '3'
services:
    gpt-pilot:
        environment:
            # OPENAI/AZURE/OPENROUTER
            - ENDPOINT=OPENAI
            - OPENAI_API_KEY=
            # - AZURE_API_KEY=
            # - AZURE_ENDPOINT=
            # - OPENROUTER_API_KEY=
            # In case of Azure endpoint, change this to your deployed model name
            - MODEL_NAME=anthropic/claude-3-haiku-20240307
            - MAX_TOKENS=8192
            - DATABASE_TYPE=postgres
            - DB_NAME=pilot
            - DB_HOST=postgres
            - DB_PORT=5432
            - DB_USER=pilot
            - DB_PASSWORD=pilot
            # Folders which shouldn't be tracked in workspace (useful to ignore folders created by compiler)
            # IGNORE_PATHS=folder1,folder2
        volumes:
            - ~/workspace:/usr/src/app/workspace
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "7681:7681"
            - "3000:3000"
            - "5173:5173"
        depends_on:
            postgres:
                condition: service_healthy
    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: pilot
            POSTGRES_PASSWORD: pilot
            POSTGRES_DB: pilot
        ports:
        - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U pilot"]
            interval: 30s
            timeout: 10s
            retries: 3
